### ISSUE TITLE
Consider to don't put all the stuff within a tmp directory

### ISSUE THREAD

**Issue by afercia** [Varying-Vagrant-Vagrants/CD-USB-Generator#10]
During the recent WordCamp Milano contributors day we've used USB sticks generated with CD-USB-Generator and I wanted to thank everyone who contributed to this script, as it makes so easy to distribute an updated, ready to use VVV.

One small thing that caused a bit of confusion during the contributor day is that unarchiving vvv.zip, everything was within a `tmp` directory. We were in doubt what to do: should the tmp folder stay as is or all the tmp content can be moved to the parent directory? Personally, I've moved the content and everything seemed to work fine. However this is a bit confusing. Not sure if there are technical reasons to have a tmp folder, wondering if this could be simplified to have the vvv.zip content extracted in the current directory or maybe add some details in the `instructions.html`.

Currently, the instructions don't mention the tmp directory:
```
11. Extract vvv.zip.
12. Now navigate into the directory that was extracted from vvv.zip The
    contents should include a file named Vagrantfile.
13. Start up Vagrant:
    ...
```

**Comment by tomjn** [comment]
It shouldn't, this is a mistake made when building the script since it's supposed to archive the contents of the `tmp` folder, not the `tmp` folder itself. I believe for Europe myself and @LoreleiAurora just rebuilt the zip file from the `tmp` folder so it worked correctly

**Comment by tomjn** [comment]
https://github.com/Varying-Vagrant-Vagrants/CD-USB-Generator/blob/master/run.sh#L28

**Comment by tomjn** [comment]
It's now a `vvv` directory, instructions adjusted
