### ISSUE TITLE
Download also git for windows

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/CD-USB-Generator#12]
I saw that this script generated everything but is missing the git client for windows that often people doesn't have (also if they are developers).
During contributor day we check that the machine are complete of tools and in case of git we can explain how to do a patch etc...

**Comment by tomjn** [comment]
hmm does git require a restart of the machine when installed on Windows?

**Comment by LoreleiAurora** [comment]
Closed in #14
