### ISSUE TITLE
Add the latest box image

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/CD-USB-Generator#13]
Often there is the connectivity issue on wordcamp so download for every laptop the image is a big problem.
This can benefit also for 3.x that will have the box image with less time on download stuff.

**Comment by tomjn** [comment]
This happens in https://github.com/Varying-Vagrant-Vagrants/CD-USB-Generator/blob/master/run.sh#L19 the output hould contain a `vvv-contribute.box` in the final USB drive contents

**Comment by tomjn** [comment]
Or do you mean the Ubuntu base image? It didn't know that was an issue

**Comment by Mte90** [comment]
I didn't know that was generating also the box for vagrant.
Maybve a guide about how to use it because usually of this pen are used only the installer for vagrant etc but that part is ignored.

**Comment by tomjn** [comment]
the vvv contribute box should contain the contents of the ubuntu base image already, so it's not an issue. The instructions should already cover this as it already asks you to add the box
