### ISSUE TITLE
Restart the script

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/CD-USB-Generator#16]
I made the build but for different reasons the generation of the image of vagrant was blocked.
So I restarted the script and I had to eliminate the part already done to speed up the procedure.
At wordcamp I saw that the image generated wasn't incomplete because the provision was incomplete.

We need to implement a way to restart from the last change!

**Comment by tomjn** [comment]
Closing this in favour of https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1988
