### ISSUE TITLE
Error on executing the script

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/CD-USB-Generator#19]
```
 default: /tmp/vagrant-shell: line 5: /vagrant/provision/resources/core/memcached-admin/provision.sh: Permission denied
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
I got that running the script, I think that is a problem of another repo anyway.

**Comment by tomjn** [comment]
Can you raise this on the main VVV repo? Along with more context for the provisioner log? Usually the cause of these things is before the error or in the first 100 or so lines of the output

**Comment by Mte90** [comment]
I can try it with a new machine anyway, but I got that running the script so maybe happen with that yml specific file?

**Comment by Mte90** [comment]
I executed manually:
```
rm -rf build vvv
mkdir -p build vvv
git clone https://github.com/Varying-Vagrant-Vagrants/VVV.git --branch=master vvv
cp resources/vvv-custom.yml vvv/vvv-custom.yml
VVV_SKIP_LOGO=true vagrant up --provision --provider=virtualbox
```
And the problem didn't happened. I am wondering if the issue happened because yesterday I launched the command inside an USB pen with a fat32 filesystem.

**Comment by Mte90** [comment]
I am trying right now from the disk, maybe we can add an alert in the readme for USB pen.

**Comment by tomjn** [comment]
If you know of a way to reliably detect that, I'd add it to VVV itself

**Comment by Mte90** [comment]
Looking on the net seems that is possible to detect when is debugged but not when we are on USB cwd.
Maybe we can use the `/mnt/` and `/media/` string to check the cwd, if include that we ask as prompt if they want to proceed and they are sure that is not an USB pen.

**Comment by LoreleiAurora** [comment]
to cover macOS `/volumes` to this list.

**Comment by Mte90** [comment]
Also I don't know why the script stopped download the binaries, so maybe we can do a check for curl about the size of that file added.
