### ISSUE TITLE
Provisioning errors on Ubuntu 15

### ISSUE THREAD

**Issue by iandunn** [Varying-Vagrant-Vagrants/CD-USB-Generator#3]
This project is a great idea and I think it'll be extremely helpful at contributor days. Kudos @LoreleiAurora :)

I installed VirtualBox 4.3.36 and Vagrant 1.6.5 on an Ubuntu laptop which has never had those before, but couldn't get the machine to boot. I haven't had time to dig in yet, but I figured I'd go ahead and start an issue to track it. I'll try to look into it later this week.

It could be https://github.com/mitchellh/vagrant/issues/4925. 1.6.5 is the latest version of Vagrant available in the Ubuntu repo, so it'd be nice to support it. I don't think many contributors will be using Linux, though, so it'd could also be enough to just make a note in `linux.txt`

<blockquote>
> vagrant up --provider virtualbox

  __     ___     ___     __  ____    
  \ \   / \ \   / \ \   / / |___ \   
   \ \ / / \ \ / / \ \ / /    __) |  
    \ V /   \ V /   \ V /    / __/   
     \_/     \_/     \_/    |_____|  

  Varying Vagrant Vagrants 2.0.0

  Docs:       https://varyingvagrantvagrants.org/
  Contribute: https://github.com/varying-vagrant-vagrants/vvv

Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'fix-no-tty' provisioner could not be found.
* The 'default' provisioner could not be found.
* The 'utility-source-core' provisioner could not be found.
* The 'utility-core-memcached-admin' provisioner could not be found.
* The 'utility-core-opcache-status' provisioner could not be found.
* The 'utility-core-phpmyadmin' provisioner could not be found.
* The 'utility-core-webgrind' provisioner could not be found.
* The 'site-wordpress-default' provisioner could not be found.
* The 'site-wordpress-develop' provisioner could not be found.
</blockquote>

**Comment by LoreleiAurora** [comment]
The linux.txt file tells you to download the latest versions of vagrant/virtualbox from there respective websites, not install from the repo.

As the main vagrant file is composed of Vagrant2 syntax it would be impossible to support such an old vagrant version.
If VVV was downgraded to support  Vagrant2 syntax (which was obsolete in 2014) then it would not run on new installs.

**Comment by iandunn** [comment]
Ah, ok. I think it's fairly common for Linux users to avoid installing things from scratch when they're available in the official repos, but maybe it's just me. I guess if it becomes a problem we can always add something to linux.txt to make it more explicit.

**Comment by iandunn** [comment]
After upgrading to Vagrant 1.9.5 everything worked fine :)
