### ISSUE TITLE
Issues with python- pip

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/CD-USB-Generator#32]
I'm trying to install python- pip but after using install this shows : 
`Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python-pip`  
So Please help me about this 👍 
@zzap @tomjn

_Originally posted by @SarveshJoshi25 in https://github.com/Varying-Vagrant-Vagrants/CD-USB-Generator/issues/31#issuecomment-500783437_

**Comment by Mte90** [comment]
@SarveshJoshi25 where are you getting this error?

**Comment by SarveshJoshi25** [comment]
On Microsoft Bash

**Comment by SarveshJoshi25** [comment]
@Mte90 Actually I Was trying to make a Twitter Bot using python 
and i tried installing python3-pip and this error occured

**Comment by Mte90** [comment]
well but this doesn't involve this project, you should open the ticket on a forum and not in the VVV project.
